changelog:
  categories:
    - title: '🚀 Features'
      labels:
        - feature
    - title: '🐛 Bug Fixes'
      labels:
        - bugfix
    - title: '🔧 Refactoring'
      labels:
        - refactor
    - title: '📖 Documentation'
      labels:
        - doc
    - title: '👒 Dependency update'
      labels:
        - deps
    - title: '🧰 Maintenance'
      labels:
        - 'maintenance'
    - title: Other Changes
      labels:
        - "*"
