[package]
name = "relentless"
version = "0.1.1"
description = "Relentless HTTP load testing / comparison testing tool"
authors = ["hayas1 <h4ystack@gmail.com>"]
edition = "2021"
repository = "https://github.com/hayas1/relentless"
license-file = "LICENSE"
readme = "README.md"

[features]
default = ["full"]
full = ["json", "yaml", "toml", "cli", "default-http-client"]

json = ["serde_json", "json-patch", "jsonptr"]
yaml = ["serde_yaml"]
cli = ["clap", "default-http-client", "console-report"]
console-report = ["console"]
default-http-client = ["reqwest"]


[dependencies]
tokio = { version = "1.41.0", features = ["full"] }
tower = { version = "0.5.0", features = ["timeout", "util"] }
reqwest = { version = "0.12.9", optional = true }
http = "1.1.0"
http-serde = "2.1.1"
http-body = "1.0.1"
http-body-util = "0.1.2"
bytes = "1.8.0"

thiserror = "1.0.68"
serde = { version = "1.0.214", features = ["derive"] }
serde_json = { version = "1.0.132", optional = true }
serde_yaml = { version = "0.9.34", optional = true }
toml = { version = "0.8.19", optional = true }
json-patch = { version = "3.0.1", optional = true }
jsonptr = { version = "0.6.3", optional = true }

clap = { version = "4.5.20", features = ["derive"], optional = true }
console = { version = "0.15.8", optional = true }


[dev-dependencies]
relentless-dev-server = { path = "dev/server" }
axum = "0.7.5"
glob = "0.3.1"
httptest = "0.16.1"
assert-json-diff = "2.0.2"
serde_json = "1.0.132"

[workspace]
members = ["dev/server"]

[badges]
github = { repository = "hayas1/relentless", workflow = "Master" }
maintenance = { status = "experimental" }
