[package]
name = "relentless"
version = "0.1.0"
description = "Relentless HTTP load testing / comparison testing tool"
authors = ["hayas1 <h4ystack@gmail.com>"]
edition = "2021"
repository = "https://github.com/hayas1/relentless"

[features]
default = ["full"]
full = ["json", "yaml", "toml", "cli"]

json = ["serde_json"]
yaml = ["serde_yaml"]
cli = ["clap"]


[dependencies]
tokio = { version = "1.40.0", features = ["full"] }
tower = { version = "0.5.0", features = ["timeout", "util"] }
reqwest = "0.12.7"
http = "1.1.0"
http-serde = "2.1.1"
http-body = "1.0.1"
http-body-util = "0.1.2"
bytes = "1.7.2"

thiserror = "1.0.63"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = { version = "1.0.128", optional = true }
serde_yaml = { version = "0.9.34", optional = true }
toml = { version = "0.8.19", optional = true }

clap = { version = "4.5.18", features = ["derive"], optional = true }
console = "0.15.8"


[dev-dependencies]
example-http-server = { path = "examples/server/http" }
axum = "0.7.5"

[workspace]
members = ["examples/server/*"]
