[package]
name = "relentless"
version = "0.1.0"
edition = "2021"

[features]
default = ["json", "yaml", "toml", "cli"]
json = ["serde_json"]
yaml = ["serde_yaml"]
cli = []                                  # TODO clap ?


[dependencies]
thiserror = "1.0.63"

tokio = { version = "1.40.0", features = ["full"] }
tower = { version = "0.5.0", features = ["timeout"] }
http = "1.1.0"
url = "2.5.2"

serde = { version = "1.0.210", features = ["derive"] }
serde_json = { version = "1.0.128", optional = true }
serde_yaml = { version = "0.9.34", optional = true }
toml = { version = "0.8.19", optional = true }
http-serde = "2.1.1"
hyper = "1.4.1"
hyper-util = { version = "0.1.8", features = ["full"] }
http-body = "1.0.1"
http-body-util = "0.1.2"
bytes = "1.7.2"


[dev-dependencies]
example-http-server = { path = "examples/server/http" }
axum = "0.7.5"
tower = { version = "0.5.1", features = ["util"] }

[workspace]
members = ["examples/server/*"]
