[package]
name = "relentless"
version = "0.1.0"
edition = "2021"

[features]
default = ["json", "yaml", "toml"]
json = ["serde_json"]
yaml = ["serde_yaml"]

[dependencies]
thiserror = "1.0.63"

tokio = { version = "1.40.0", features = ["full"] }
reqwest = "0.12.7"
tower = { version = "0.5.0", features = ["timeout"] }
http = "1.1.0"
url = "2.5.2"

serde = { version = "1.0.210", features = ["derive"] }
serde_json = { version = "1.0.128", optional = true }
serde_yaml = { version = "0.9.34", optional = true }
toml = { version = "0.8.19", optional = true }
http-serde = "2.1.1"

[dev-dependencies]
example-http-server = { path = "examples/server/http" }
axum = "0.7.5"
tower = { version = "0.5.1", features = ["util"] }

[workspace]
members = ["examples/server/*"]
