[package]
name = "relentless"
version = "0.1.5"
description = "Relentless HTTP load testing / comparison testing tool"
authors = ["hayas1 <h4ystack@gmail.com>"]
edition = "2021"
repository = "https://github.com/hayas1/relentless"
license-file = "LICENSE"
readme = "README.md"

[features]
default = ["full"]
full = ["json", "yaml", "toml", "cli", "default-http-client"]

json = ["serde_json", "json-patch", "jsonptr"]
yaml = ["serde_yaml"]
cli = ["clap", "default-http-client", "console-report"]
console-report = ["console"]
default-http-client = ["reqwest"]


[dependencies]
tokio = { version = "1.42.0", features = ["full"] }
# tokio-stream = "0.1.17" # TODO map of tokio-stream may not collect as Vec<T>Item (it reduce Vec<Future>), so use futures
futures = "0.3.31"
tower = { version = "0.5.2", features = ["timeout", "util"] }
reqwest = { version = "0.12.9", optional = true }
http = "1.2.0"
http-serde = "2.1.1"
http-body = "1.0.1"
http-body-util = "0.1.2"
mime = "0.3.17"
bytes = "1.9.0"

thiserror = "2.0.7"
regex = "1.11.1"
serde = { version = "1.0.216", features = ["derive"] }
serde_json = { version = "1.0.133", optional = true }
serde_yaml = { version = "0.9.34", optional = true }
toml = { version = "0.8.19", optional = true }
json-patch = { version = "3.0.1", optional = true }
jsonptr = { version = "0.6.3", optional = true }

clap = { version = "4.5.23", features = ["derive"], optional = true }
console = { version = "0.15.10", optional = true }
nom = "7.1.3"
average = "0.15.1"


[dev-dependencies]
relentless-dev-server = { path = "dev/server" }
axum = "0.7.9"
glob = "0.3.1"
httptest = "0.16.1"
assert-json-diff = "2.0.2"
serde_json = "1.0.133"
indoc = "2.0.5"

[workspace]
members = ["dev/server"]

[badges]
github = { repository = "hayas1/relentless", workflow = "Master" }
maintenance = { status = "experimental" }
