name: basic grpc assault test
destinations:
  test-api: http://localhost:50051

testcases:
  - target: greeter.Greeter/SayHello
    setting:
      request:
        message:
          json:
            name: John Doe
