name: basic grpc comparison test
destinations:
  actual: http://localhost:50051
  expect: http://localhost:50051

testcases:
  - target: greeter.Greeter/SayHello
    setting:
      request:
        message:
          json:
            name: John Doe
