name: basic grpc comparison test
destinations:
  actual: http://localhost:50051
  expect: http://localhost:50051

testcases:
  - target: greeter.Greeter/SayHello
    setting:
      request:
        descriptor:
          protos: [./dev/server/grpc/proto/greeter.proto]
          import_path: [./dev/server/grpc/proto]
        message:
          json:
            name: John Doe
