name: basic grpc shot test
destinations:
  test-api: http://localhost:50051
contract:
  proto-files:
    protos:
      - ./dev/server/grpc/proto/greeter.proto
      - ./dev/server/grpc/proto/echo.proto
    includes: [./dev/server/grpc/proto]

testcases:
  - target: greeter.Greeter/SayHello
    profile:
      request:
        message:
          json:
            name: John Doe
  - target: echo.Echo/Echo
    profile:
      request:
        message:
          json: 100

