name: example yaml of basic assault test
setting:
  host:
    test-api: http://localhost:3000


testcase:
  - target: /
  - target: /health
  - target: /healthz
  - target: /health/rich
  - target: /health/disabled
