name: example yaml of basic json assault test
destinations:
  test-api: http://localhost:3000
setting:
  repeat: 10


testcase:
  - target: /health/rich
    description: request to root
    setting:
      repeat: 100
      json:
        patch:
        - op: test
          path: /
          value:
            status: 200 OK
            code: 200
