name: example yaml of basic assault test
setting:
  origin:
    test-api: http://localhost:3000


testcase:
  - target: /
  - target: /health
  - target: /healthz
  - target: /health/rich
  - target: /health/disabled
    description: this endpoint will respond with 503 service unavailable
    attr:
      invalid: true
