name: example yaml of basic json compare test
destinations:
  actual: http://localhost:3000
  expect: http://localhost:3000


testcase:
  - target: /counter/increment
    setting:
      repeat: 10
    attr:
      allow: true
  - target: /health/rich
  - target: /information
    description: ignore datetime and hostname
    setting:
      json:
        ignore:
        - /datetime
        - /hostname
        - /headers/host
  - target: /information
    description: do not ignore datetime and hostname (must be failed, so attr allowed)
    attr:
      allow: true
  - target: /information
    description: patch datetime and hostname
    setting:
      json:
        patch:
        - {"op": "replace", "path": "/datetime", "value": "2024-10-10T00:00:00Z"}
        - {"op": "remove", "path": "/hostname"}
        - {"op": "replace", "path": "/headers/host", "value": "127.0.0.1:3000"}
        - {"op": "test", "path": "/path", "value": "/information"}
  - target: /information
    description: remove actual datetime only (must be failed, so attr allowed)
    setting:
      json:
        patch:
          actual:
          - op: remove
            path: /datetime
    attr:
      allow: true
