name: example yaml of basic compare test
destinations:
  actual: http://localhost:3000
  expect: http://localhost:3000
# setting:
#   template:
#     version:
#       actual: v1
#       expect: v2


testcase:
  - target: /
  - target: /
    description: test description
    setting:
      http:
        method: GET
  - target: /counter/increment
    setting:
      repeat: 10
    attr:
      allow: true
  - target: /health/rich
  - target: /information
    description: ignore datetime
    setting:
      json:
        ignore:
        - /datetime
  - target: /information
    description: do not ignore datetime
    attr:
      allow: true
  - target: /information
    description: patch datetime
    setting:
      json:
        patch:
        - op: replace
          path: /datetime
          value: 2024-10-10
  - target: /information
    description: remove actual datetime (must be failed, so allowed attr)
    setting:
      json:
        patch:
          actual:
          - op: remove
            path: /datetime
    attr:
      allow: true
