name: example yaml of basic compare test
origins:
  actual: http://localhost:3000
  expect: http://localhost:3000
setting:
  template:
    version:
      actual: v1
      expect: v2


testcase:
  - target: /
  - target: /
    description: test description
    setting:
      http:
        method: GET
