name: Run Example Http Server

inputs:
  manifest-path:
    description: Manifest path to Cargo.toml of the example http server
    required: false
    default: examples/server/http/Cargo.toml
  port:
    description: Port to listen on
    required: false
    default: 3000

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - name: Cargo home
      shell: bash
      id: cargo-home
      run: echo "path=${CARGO_HOME:-~/.cargo}" >>"$GITHUB_OUTPUT"
    - uses: actions/cache@v4
      with:
        path: |
          target
          ${{ steps.cargo-home.outputs.path }}
        key: cargo-${{ hashFiles('**/Cargo.toml') }}

    - name: Run example http server
      shell: bash
      env:
        PORT: ${{ inputs.port }}
      run: cargo run --manifest-path ${{ inputs.working-directory }}/Cargo.toml&
