[package]
name = "relentless-dev-server-http"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.8.1", features = ["tokio", "original-uri"] }
axum-extra = "0.10.0"
chrono = { version = "0.4.39", features = ["serde"] }
http-serde = "2.1.1"
num = { version = "0.4.3", features = ["serde"] }
rand = "0.8.5"
rand_distr = "0.4.3"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.135"
# serde_qs = "0.13.0"
serde_urlencoded = "0.7.1"
thiserror = "2.0.11"
tokio = { version = "1.43.0", features = ["full"] }
tower = { version = "0.5.2", features = ["util"] }
tower-http = { version = "0.6.2", features = ["normalize-path"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"

[dev-dependencies]
mime = "0.3.17"
