[package]
name = "relentless-grpc-dev-server"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license-file.workspace = true

[dependencies]
prost = "0.13.5"
prost-types = "0.13.5"
tonic = "0.12.3"
tonic-health = "0.12.3"
tonic-reflection = "0.12.3"
tower = "0.5.2"
tokio = { version = "1.43.0", features = [
    "macros",
    "rt-multi-thread",
    "signal",
] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"

num = "0.4.3"
thiserror = "2.0.12"

[build-dependencies]
tonic-build = "0.12.3"
