[package]
name = "relentless-dev-server-grpc"
version = "0.1.0"
edition = "2021"

[dependencies]
relentless-dev-server-grpc-entity = { path = "./entity" }
prost = "0.13.4"
tonic = "0.12.3"
tower = "0.5.2"
tokio = { version = "1.42.0", features = ["macros", "rt-multi-thread", "signal"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"

num = "0.4.3"
thiserror = "2.0.9"

